#!/usr/bin/env python3
"""
json_flatten.py

Generated by Claude: Sonnet 4.6 (low)

Reads a JSON file and emits a depth-first list of (path, value) pairs:

    path<kv_delim>value<row_delim>path<kv_delim>value<row_delim>...

All three delimiters are configurable:
  --path-delim : joins the segments of a key's path (default ".")
  --kv-delim   : separates the path from its value     (default ": ")
  --row-delim  : separates one path/value row from the next (default "\\n")

List elements get a path segment like "[0]", "[1]", etc., so an
array nested under "a" looks like "a[0]", "a[1]", ... by default.

Examples
--------
  python json_flatten.py data.json
  python json_flatten.py data.json --path-delim "/" --kv-delim "=" --row-delim ";"
  python json_flatten.py data.json -o flat.txt

  -or-

  uv run json_flatten.py data.json
  uv run json_flatten.py data.json --path-delim "/" --kv-delim "=" --row-delim ";"
  uv run json_flatten.py data.json -o flat.txt
"""

import argparse
import json
import sys


def unescape(s: str) -> str:
    """Allow users to type things like \\n or \\t on the command line
    and have them turned into actual newline/tab characters."""
    return s.encode("utf-8").decode("unicode_escape")


def format_value(value) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    return str(value)


def join_path(path, path_delim):
    """Join path segments with path_delim, but don't put a delimiter
    right before an array index segment like '[0]' (so you get
    'pets[0]' rather than 'pets.[0]')."""
    parts = []
    for i, segment in enumerate(path):
        if i > 0 and not segment.startswith("["):
            parts.append(path_delim)
        parts.append(segment)
    return "".join(parts)


def emit(path, value, path_delim, kv_delim, row_delim, out):
    path_str = join_path(path, path_delim)
    out.write(f"{path_str}{kv_delim}{format_value(value)}{row_delim}")


def walk(node, path, path_delim, kv_delim, row_delim, out):
    """Depth-first traversal. Writes one row per leaf value encountered.
    Empty dicts/lists are treated as leaves (with value {} or [])
    so they aren't silently dropped from the output."""

    if isinstance(node, dict):
        if not node:
            emit(path, "{}", path_delim, kv_delim, row_delim, out)
            return
        for key, value in node.items():
            walk(value, path + [str(key)], path_delim, kv_delim, row_delim, out)

    elif isinstance(node, list):
        if not node:
            emit(path, "[]", path_delim, kv_delim, row_delim, out)
            return
        for i, value in enumerate(node):
            walk(value, path + [f"[{i}]"], path_delim, kv_delim, row_delim, out)

    else:
        emit(path, node, path_delim, kv_delim, row_delim, out)


def main():
    parser = argparse.ArgumentParser(
        description="Depth-first flatten a JSON file into path/value rows."
    )
    parser.add_argument("json_file", help="Path to the input JSON file")
    parser.add_argument(
        "--path-delim",
        default=".",
        help="Delimiter between path segments (default: '.')",
    )
    parser.add_argument(
        "--kv-delim",
        default=": ",
        help="Delimiter between the path and the value (default: ': ')",
    )
    parser.add_argument(
        "--row-delim",
        default="\\n",
        help=r"Delimiter between rows (default: newline). "
        r"Escape sequences like \n or \t are interpreted, "
        r"so you can pass --row-delim '\n\n' for blank lines between rows.",
    )
    parser.add_argument(
        "-o",
        "--output",
        help="Output file (default: stdout)",
    )
    args = parser.parse_args()

    path_delim = unescape(args.path_delim)
    kv_delim = unescape(args.kv_delim)
    row_delim = unescape(args.row_delim)

    with open(args.json_file, "r", encoding="utf-8") as f:
        data = json.load(f)

    out = open(args.output, "w", encoding="utf-8") if args.output else sys.stdout
    try:
        walk(data, [], path_delim, kv_delim, row_delim, out)
    finally:
        if args.output:
            out.close()


if __name__ == "__main__":
    main()
